"""create all tables

Revision ID: b25b93865787
Revises: ca1814bc041c
Create Date: 2025-11-16 22:01:58.360853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b25b93865787'
down_revision: Union[str, Sequence[str], None] = 'ca1814bc041c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_veiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_veiculos_id'), 'categorias_veiculos', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_veiculos_nome'), 'categorias_veiculos', ['nome'], unique=True)
    op.create_table('enderecos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rua', sa.String(length=120), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_id'), 'enderecos', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco_id', sa.UUID(), nullable=True),
    sa.Column('cnh_numero', sa.String(length=20), nullable=False),
    sa.Column('cnh_validade', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh_numero')
    )
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=True)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('lojas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lojas_id'), 'lojas', ['id'], unique=False)
    op.create_table('veiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('ano', sa.SmallInteger(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('diaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('DISPONIVEL', 'ALUGADO', 'RESERVADO', 'MANUTENCAO', 'FORA_AREA', name='status_veiculo'), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_veiculos.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_id'), 'veiculos', ['id'], unique=False)
    op.create_index(op.f('ix_veiculos_placa'), 'veiculos', ['placa'], unique=True)
    op.create_table('historico_status_veiculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('veiculo_id', sa.UUID(), nullable=False),
    sa.Column('status_anterior', postgresql.ENUM('DISPONIVEL', 'ALUGADO', 'RESERVADO', 'MANUTENCAO', 'FORA_AREA', name='status_veiculo'), nullable=True),
    sa.Column('status_atual', postgresql.ENUM('DISPONIVEL', 'ALUGADO', 'RESERVADO', 'MANUTENCAO', 'FORA_AREA', name='status_veiculo'), nullable=False),
    sa.Column('data_mudanca', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_status_veiculo_id'), 'historico_status_veiculo', ['id'], unique=False)
    op.create_index(op.f('ix_historico_status_veiculo_veiculo_id'), 'historico_status_veiculo', ['veiculo_id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('veiculo_id', sa.UUID(), nullable=False),
    sa.Column('loja_retirada_id', sa.UUID(), nullable=False),
    sa.Column('loja_devolucao_id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('periodo', sa.SmallInteger(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motorista_incluido', sa.Boolean(), nullable=False),
    sa.Column('canal_origem', postgresql.ENUM('WEB', 'LOJA', 'TELEFONE', name='canal_origem'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDENTE_PAGAMENTO', 'CONFIRMADA', 'EM_CURSO', 'FINALIZADA', 'CANCELADA', name='status_reserva'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('periodo IN (7, 15, 30)', name='check_periodo_valido'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['loja_devolucao_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['loja_retirada_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('metodo', postgresql.ENUM('CARTAO', name='metodo_pagamento'), nullable=False),
    sa.Column('status', postgresql.ENUM('PAGO', 'PENDENTE', 'RECUSADO', name='status_pagamento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transacao_gateway_id', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id'),
    sa.UniqueConstraint('transacao_gateway_id')
    )
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_historico_status_veiculo_veiculo_id'), table_name='historico_status_veiculo')
    op.drop_index(op.f('ix_historico_status_veiculo_id'), table_name='historico_status_veiculo')
    op.drop_table('historico_status_veiculo')
    op.drop_index(op.f('ix_veiculos_placa'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_id'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_lojas_id'), table_name='lojas')
    op.drop_table('lojas')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_enderecos_id'), table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_index(op.f('ix_categorias_veiculos_nome'), table_name='categorias_veiculos')
    op.drop_index(op.f('ix_categorias_veiculos_id'), table_name='categorias_veiculos')
    op.drop_table('categorias_veiculos')
    # ### end Alembic commands ###
