"""create missing tables

Revision ID: d81083056a7f
Revises: b25b93865787
Create Date: 2025-11-16 22:26:07.141987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81083056a7f'
down_revision: Union[str, Sequence[str], None] = 'b25b93865787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculos', sa.Column('cor', sa.String(length=30), nullable=True))
    op.add_column('veiculos', sa.Column('combustivel', sa.String(length=30), nullable=True))
    op.add_column('veiculos', sa.Column('portas', sa.SmallInteger(), nullable=True))
    op.add_column('veiculos', sa.Column('cambio', sa.String(length=30), nullable=True))
    op.add_column('veiculos', sa.Column('quilometragem', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculos', 'quilometragem')
    op.drop_column('veiculos', 'cambio')
    op.drop_column('veiculos', 'portas')
    op.drop_column('veiculos', 'combustivel')
    op.drop_column('veiculos', 'cor')
    # ### end Alembic commands ###
